<#  Write-KnowledgeTable.ps1 — regenerate knowledge/KNOWLEDGE.md from registry.json,
    grouped by domain. Generated artifact — never hand-edited. #>
[CmdletBinding()]
param([string]$Root = (Get-Location).Path)
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'KnowledgeRegistryIo.ps1')
$regPath = Resolve-KnowledgeRegistryPath -Root $Root
if (-not (Test-Path -LiteralPath $regPath)) { throw "No registry at $regPath" }
$reg = Read-KnowledgeRegistry -Path $regPath
$refs = @($reg.references)

function Format-Ref { param([string]$s) if ($s -match '^(https?)://') { "[$s]($s)" } else { "``$s``" } }
function Format-Cell { param([string]$s) ([string]$s -replace '\|','\|') }

$sb = [Text.StringBuilder]::new()
[void]$sb.AppendLine("<!-- GENERATED by /knowledge — do not edit by hand. Source: knowledge/registry.json -->")
[void]$sb.AppendLine("# Knowledge — $($reg.project)")
[void]$sb.AppendLine("")
if ($refs.Count -eq 0) {
    [void]$sb.AppendLine("_No references yet. Add one with ``/knowledge add``._")
} else {
    foreach ($domain in ($refs | Select-Object -ExpandProperty domain -Unique | Sort-Object)) {
        [void]$sb.AppendLine("## $domain")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("| Title | Type | Ref | Note |")
        [void]$sb.AppendLine("|-------|------|-----|------|")
        foreach ($r in ($refs | Where-Object domain -eq $domain | Sort-Object title)) {
            [void]$sb.AppendLine(("| {0} | {1} | {2} | {3} |" -f (Format-Cell $r.title), $r.type, (Format-Ref $r.ref), (Format-Cell $r.note)))
        }
        [void]$sb.AppendLine("")
    }
}
$outPath = Join-Path $Root 'knowledge' 'KNOWLEDGE.md'
$sb.ToString() | Set-Content -LiteralPath $outPath -Encoding utf8
$outPath
