#Requires -Modules Pester
<#  Pester tests for Publish-DocsWiki.ps1 page generation (-PagesOnly, no git/network).
    Validates:
      - Docs-Home is generated from README.md (HTML stripped, GENERATED marker present)
      - Knowledge registry pages (Home + Knowledge-<Domain>) when registry.json exists
      - _Sidebar and _Footer navigation pages
      - Empty states: README with only HTML still produces a Docs-Home
      - Uninitialized wiki produces an actionable error with the wiki URL

    Note: Docs-Command-* pages were dropped in #418.  commands/*.md are agent instruction
    files (system prompts), not documentation.  Verifying that a page "generates" was never
    evidence that it "reads" — a 31 KB dump of internal recipes passes the GENERATED marker
    check while being worse than nothing as documentation.  The generator was removed; for
    code and architecture reference, route users to DeepWiki instead.
#>
BeforeAll {
    $script:Engine = Join-Path $PSScriptRoot '..' 'scripts' 'Publish-DocsWiki.ps1' | Resolve-Path

    # Helper: run the script in -PagesOnly mode and return a hashtable of page-name -> content
    function Invoke-PagesOnly {
        param(
            [string]$Root,
            [string]$OutDir = (Join-Path $Root 'out')
        )
        & $script:Engine -Root $Root -OutDir $OutDir -PagesOnly | Out-Null
        $pages = @{}
        foreach ($f in (Get-ChildItem -LiteralPath $OutDir -Filter '*.md' -File)) {
            $pages[$f.BaseName] = Get-Content -LiteralPath $f.FullName -Raw
        }
        $pages
    }

    # Helper: compute expected extra page count from knowledge registry at given root
    function Get-KnowledgePageCount {
        param([string]$Root)
        $regPath     = Join-Path $Root 'knowledge' 'registry.json'
        $regPathYaml = Join-Path $Root 'knowledge' 'registry.yaml'
        $rp = if (Test-Path -LiteralPath $regPath) { $regPath }
              elseif (Test-Path -LiteralPath $regPathYaml) { $regPathYaml }
              else { $null }
        if (-not $rp) { return 0 }
        $reg = Get-Content -LiteralPath $rp -Raw | ConvertFrom-Json -ErrorAction SilentlyContinue
        if (-not $reg) { return 0 }
        $domains = @($reg.references | Select-Object -ExpandProperty domain -Unique)
        if ($domains.Count -eq 0) { return 1 }  # Home only when empty registry
        return 1 + $domains.Count                # Home + one per domain
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — page set' {
    BeforeAll {
        # Use the real README.md from the repo root (three levels up from tests/)
        $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:Out      = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-out-" + [guid]::NewGuid().ToString('N'))
        $script:Pages    = Invoke-PagesOnly -Root $script:RepoRoot -OutDir $script:Out
    }
    AfterAll { if ($script:Out -and (Test-Path $script:Out)) { Remove-Item $script:Out -Recurse -Force } }

    It 'generates Docs-Home' {
        $script:Pages.Keys | Should -Contain 'Docs-Home'
    }

    It 'does NOT generate any Docs-Command-* pages' {
        $cmdPages = @($script:Pages.Keys | Where-Object { $_ -like 'Docs-Command-*' })
        $cmdPages | Should -BeNullOrEmpty -Because 'commands/*.md are agent prompts, not documentation (#418)'
    }

    It 'generates _Sidebar navigation page' {
        $script:Pages.Keys | Should -Contain '_Sidebar'
    }

    It 'generates _Footer page' {
        $script:Pages.Keys | Should -Contain '_Footer'
    }

    It 'generates exactly 3 + (knowledge pages) total pages' {
        $knExtra = Get-KnowledgePageCount -Root $script:RepoRoot
        # Fixed set: Docs-Home + _Sidebar + _Footer (+ optional knowledge pages)
        $script:Pages.Count | Should -Be (3 + $knExtra)
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — Docs-Home content' {
    BeforeAll {
        $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:Out      = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-home-" + [guid]::NewGuid().ToString('N'))
        $script:Pages    = Invoke-PagesOnly -Root $script:RepoRoot -OutDir $script:Out
        $script:DocsHomePage = $script:Pages['Docs-Home']
    }
    AfterAll { if ($script:Out -and (Test-Path $script:Out)) { Remove-Item $script:Out -Recurse -Force } }

    It 'carries the GENERATED do-not-edit marker' {
        $script:DocsHomePage | Should -Match 'GENERATED by /docs wiki'
    }

    It 'strips <p> HTML blocks' {
        $script:DocsHomePage | Should -Not -Match '<p\b'
        $script:DocsHomePage | Should -Not -Match '</p>'
    }

    It 'strips <img> HTML elements' {
        $script:DocsHomePage | Should -Not -Match '<img\b'
    }

    It 'strips <sub> blocks (README version footer)' {
        $script:DocsHomePage | Should -Not -Match '<sub>'
        $script:DocsHomePage | Should -Not -Match '</sub>'
    }

    It 'retains key README prose (not blanked out)' {
        $script:DocsHomePage | Should -Match 'agentic-board'
    }

    It 'does NOT link to any Docs-Command-* page' {
        $script:DocsHomePage | Should -Not -Match 'Docs-Command-' -Because 'command pages were dropped in #418'
    }

    It 'contains a "Last published" datestamp' {
        $script:DocsHomePage | Should -Match 'Last published \d{4}-\d{2}-\d{2}'
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — knowledge registry pages' {
    BeforeAll {
        $script:RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:Out      = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-kn-" + [guid]::NewGuid().ToString('N'))
        $script:Pages    = Invoke-PagesOnly -Root $script:RepoRoot -OutDir $script:Out
        # Determine whether the registry is present and its domains
        $regPath = Join-Path $script:RepoRoot 'knowledge' 'registry.json'
        $script:HasRegistry = Test-Path -LiteralPath $regPath
        if ($script:HasRegistry) {
            $reg = Get-Content -LiteralPath $regPath -Raw | ConvertFrom-Json
            $script:KnDomains = @($reg.references | Select-Object -ExpandProperty domain -Unique | Sort-Object)
        }
    }
    AfterAll { if ($script:Out -and (Test-Path $script:Out)) { Remove-Item $script:Out -Recurse -Force } }

    It 'generates a Knowledge Home page when registry.json exists' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $script:Pages.Keys | Should -Contain 'Home'
    }

    It 'Knowledge Home carries the GENERATED marker' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $script:Pages['Home'] | Should -Match 'GENERATED by /docs wiki'
    }

    It 'generates one Knowledge-<Domain> page per domain in the registry' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $pages = $script:Pages
        foreach ($domain in $script:KnDomains) {
            $slug = 'Knowledge-' + (($domain -replace '[^\w-]+', '-') -replace '-+', '-').Trim('-')
            $pages.Keys | Should -Contain $slug -Because "domain '$domain' must produce a wiki page"
        }
    }

    It 'each Knowledge domain page back-links to Home' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $pages = $script:Pages
        foreach ($key in ($pages.Keys | Where-Object { $_ -like 'Knowledge-*' })) {
            $pages[$key] | Should -Match '\[← Home\]\(Home\)' -Because "$key must link back to Home"
        }
    }

    It 'Knowledge Home links to each domain page' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $homePage = $script:Pages['Home']
        foreach ($domain in $script:KnDomains) {
            $slug = 'Knowledge-' + (($domain -replace '[^\w-]+', '-') -replace '-+', '-').Trim('-')
            $homePage | Should -Match ([regex]::Escape("($slug)")) -Because "Home must link to $slug"
        }
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — _Sidebar content' {
    BeforeAll {
        $script:RepoRoot  = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:Out       = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-sidebar-" + [guid]::NewGuid().ToString('N'))
        $script:Pages     = Invoke-PagesOnly -Root $script:RepoRoot -OutDir $script:Out
        $script:SidebarPage = $script:Pages['_Sidebar']
        # Determine knowledge domains for sidebar link check
        $regPath = Join-Path $script:RepoRoot 'knowledge' 'registry.json'
        $script:HasRegistry = Test-Path -LiteralPath $regPath
        if ($script:HasRegistry) {
            $reg = Get-Content -LiteralPath $regPath -Raw | ConvertFrom-Json
            $script:KnDomains = @($reg.references | Select-Object -ExpandProperty domain -Unique | Sort-Object)
        }
    }
    AfterAll { if ($script:Out -and (Test-Path $script:Out)) { Remove-Item $script:Out -Recurse -Force } }

    It 'carries the GENERATED marker' {
        $script:SidebarPage | Should -Match 'GENERATED by /docs wiki'
    }

    It 'contains a Product Docs section' {
        $script:SidebarPage | Should -Match '## Product Docs'
    }

    It 'links to Docs-Home' {
        $script:SidebarPage | Should -Match '\[Home\]\(Docs-Home\)'
    }

    It 'does NOT link to any Docs-Command-* page' {
        $script:SidebarPage | Should -Not -Match 'Docs-Command-' -Because 'command pages were dropped in #418'
    }

    It 'contains a Knowledge section linking to Home' {
        $script:SidebarPage | Should -Match '## Knowledge'
        $script:SidebarPage | Should -Match '\[Knowledge\]\(Home\)'
    }

    It 'lists each knowledge domain in the sidebar when registry exists' {
        if (-not $script:HasRegistry) { Set-ItResult -Skipped -Because 'no knowledge/registry.json in this repo' ; return }
        $sidebar = $script:SidebarPage
        foreach ($domain in $script:KnDomains) {
            $slug = 'Knowledge-' + (($domain -replace '[^\w-]+', '-') -replace '-+', '-').Trim('-')
            $sidebar | Should -Match ([regex]::Escape("($slug)")) -Because "_Sidebar must link to domain $domain"
        }
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — _Footer content' {
    BeforeAll {
        $script:RepoRoot   = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:Out        = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-footer-" + [guid]::NewGuid().ToString('N'))
        $script:Pages      = Invoke-PagesOnly -Root $script:RepoRoot -OutDir $script:Out
        $script:FooterPage = $script:Pages['_Footer']
    }
    AfterAll { if ($script:Out -and (Test-Path $script:Out)) { Remove-Item $script:Out -Recurse -Force } }

    It 'carries the GENERATED marker' {
        $script:FooterPage | Should -Match 'GENERATED by /docs wiki'
    }

    It 'warns that edits here will be overwritten' {
        $script:FooterPage | Should -Match 'generated from the repository'
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — error cases' {
    It 'throws when README.md is missing' {
        $root = Join-Path ([IO.Path]::GetTempPath()) ("docswiki-normd-" + [guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $root -Force | Out-Null
        try {
            { & $script:Engine -Root $root -OutDir (Join-Path $root 'out') -PagesOnly } |
                Should -Throw -ExpectedMessage '*README.md not found*'
        } finally {
            Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    It 'throws when -PagesOnly is given without -OutDir' {
        $root = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        { & $script:Engine -Root $root -PagesOnly } | Should -Throw -ExpectedMessage '*-PagesOnly requires -OutDir*'
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-DocsWiki — uninitialized wiki error' {
    BeforeAll {
        $script:UninitRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))
        $script:PriorGit   = Get-Item 'Function:git' -ErrorAction SilentlyContinue
        $script:PriorGh    = Get-Item 'Function:gh'  -ErrorAction SilentlyContinue

        function global:git {
            if ('clone' -in $args) { $global:LASTEXITCODE = 128; return }
            $global:LASTEXITCODE = 0
        }
        function global:gh {
            if ($args[0] -eq 'api' -and 'user' -in $args) { Write-Output 'test-user' }
            elseif ($args[0] -eq 'api') { Write-Output '{"has_wiki":true,"permissions":{"push":true},"name":"test"}' }
            $global:LASTEXITCODE = 0
        }
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_DOCS_TOKEN', 'fake-unit-test-token', 'User')
    }
    AfterAll {
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_DOCS_TOKEN', $null, 'User')
        Remove-Item Env:GH_TOKEN -ErrorAction SilentlyContinue
        Remove-Item 'Function:git' -ErrorAction SilentlyContinue
        Remove-Item 'Function:gh'  -ErrorAction SilentlyContinue
        if ($script:PriorGit) { New-Item -Path 'Function:git' -Value $script:PriorGit.ScriptBlock -Force | Out-Null }
        if ($script:PriorGh)  { New-Item -Path 'Function:gh'  -Value $script:PriorGh.ScriptBlock  -Force | Out-Null }
    }

    It 'throws with an actionable step to create the first wiki page via web UI' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-docs-repo' -TokenVar ABIOS_TEST_DOCS_TOKEN } |
            Should -Throw -ExpectedMessage '*Create the first page*'
    }

    It 'error message includes the wiki URL so the user can navigate directly' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-docs-repo' -TokenVar ABIOS_TEST_DOCS_TOKEN } |
            Should -Throw -ExpectedMessage '*github.com/test-owner/test-docs-repo/wiki*'
    }
}
