#Requires -Modules Pester
<#  Pester tests for Publish-KnowledgeWiki.ps1.

    Since #405, Publish-KnowledgeWiki.ps1 is a thin alias that delegates entirely to
    Publish-DocsWiki.ps1 (single-publisher refactor). These tests verify that:
      - Delegation works: calling -PagesOnly generates the full wiki set (docs + knowledge)
      - Knowledge pages (Home + Knowledge-<Domain>) are present in the output
      - Knowledge Home carries the GENERATED marker
      - Knowledge domain pages back-link to Home
      - The uninitialized-wiki error still surfaces correctly through the delegate
    The page-generation internals are tested exhaustively in Publish-DocsWiki.Tests.ps1.
#>
BeforeAll {
    $script:Engine     = Join-Path $PSScriptRoot '..' 'scripts' 'Publish-KnowledgeWiki.ps1' | Resolve-Path
    $script:DocsEngine = Join-Path $PSScriptRoot '..' 'scripts' 'Publish-DocsWiki.ps1'     | Resolve-Path
    $script:RepoRoot   = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..'))

    function New-KnRoot {
        $root = Join-Path ([IO.Path]::GetTempPath()) ("knwiki-t-" + [guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $root -Force | Out-Null
        $root
    }
    function Seed-Registry {
        param($root, $refs)
        New-Item -ItemType Directory -Path (Join-Path $root 'knowledge') -Force | Out-Null
        ([pscustomobject]@{ version=1; project='fix'; domains=@('Fabric','Power-Query'); references=$refs }) |
            ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $root 'knowledge' 'registry.json') -Encoding utf8
        # The script discovers commands relative to PSScriptRoot, and README from -Root.
        # Provide a minimal README so the product-docs section generates without error.
        '# Test Repo' | Set-Content -LiteralPath (Join-Path $root 'README.md') -Encoding utf8
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-KnowledgeWiki (delegates to single publisher)' {
    BeforeAll {
        $script:Root = New-KnRoot
        Seed-Registry $script:Root @(
            [pscustomobject]@{ id='kn_001'; domain='Fabric';      type='url'; title='Cap API'; ref='https://learn.microsoft.com/x'; note='trial->prod'; added='2026-07-07' }
            [pscustomobject]@{ id='kn_002'; domain='Power-Query'; type='md';  title='PQ Notes'; ref='docs/pq.md';                    note='mine';        added='2026-07-07' }
        )
        $script:Out = Join-Path $script:Root 'out'
        & $script:Engine -Root $script:Root -OutDir $script:Out -PagesOnly -Date '2026-07-08' | Out-Null
        $script:AllPages = @{}
        foreach ($f in (Get-ChildItem -LiteralPath $script:Out -Filter '*.md' -File)) {
            $script:AllPages[$f.BaseName] = Get-Content -LiteralPath $f.FullName -Raw
        }
    }
    AfterAll { if ($script:Root -and (Test-Path $script:Root)) { Remove-Item $script:Root -Recurse -Force } }

    It 'produces a Home page' {
        $script:AllPages.Keys | Should -Contain 'Home'
    }

    It 'produces a Knowledge-Fabric page' {
        $script:AllPages.Keys | Should -Contain 'Knowledge-Fabric'
    }

    It 'produces a Knowledge-Power-Query page' {
        $script:AllPages.Keys | Should -Contain 'Knowledge-Power-Query'
    }

    It 'also produces product docs pages (single-publisher combines both sets)' {
        $script:AllPages.Keys | Should -Contain 'Docs-Home'
    }

    It 'Knowledge Home carries the GENERATED marker' {
        $script:AllPages['Home'] | Should -Match 'GENERATED by /docs wiki'
    }

    It 'links Home to each domain page by slug' {
        $script:AllPages['Home'] | Should -Match '\[Fabric\]\(Knowledge-Fabric\)'
        $script:AllPages['Home'] | Should -Match '\[Power-Query\]\(Knowledge-Power-Query\)'
    }

    It 'reports the reference and domain counts on Home' {
        $script:AllPages['Home'] | Should -Match '2 reference\(s\) across 2 domain\(s\)'
    }

    It 'renders urls as links on the domain page' {
        $script:AllPages['Knowledge-Fabric'] | Should -Match '\[https://learn\.microsoft\.com/x\]\(https://learn\.microsoft\.com/x\)'
    }

    It 'renders local refs as inline code on the domain page' {
        $script:AllPages['Knowledge-Power-Query'] | Should -Match '`docs/pq\.md`'
    }

    It 'back-links each domain page to Home' {
        $script:AllPages['Knowledge-Fabric']      | Should -Match '\[← Home\]\(Home\)'
        $script:AllPages['Knowledge-Power-Query'] | Should -Match '\[← Home\]\(Home\)'
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-KnowledgeWiki (empty registry)' {
    It 'produces a Home page inviting the first add' {
        $root = New-KnRoot
        Seed-Registry $root @()
        $out = Join-Path $root 'out'
        & $script:Engine -Root $root -OutDir $out -PagesOnly | Out-Null
        $pageNames = Get-ChildItem -LiteralPath $out -Filter *.md | Select-Object -ExpandProperty BaseName
        $pageNames | Should -Contain 'Home'
        (Get-Content -LiteralPath (Join-Path $out 'Home.md') -Raw) | Should -Match 'No references yet'
        Remove-Item $root -Recurse -Force
    }
    It 'produces product docs pages even when there is no registry (graceful skip)' {
        $root = New-KnRoot
        '# Readme' | Set-Content -LiteralPath (Join-Path $root 'README.md') -Encoding utf8
        $out = Join-Path $root 'out'
        & $script:Engine -Root $root -OutDir $out -PagesOnly | Out-Null
        $pageNames = Get-ChildItem -LiteralPath $out -Filter *.md | Select-Object -ExpandProperty BaseName
        # No registry → knowledge pages absent; product docs pages always present
        $pageNames | Should -Contain 'Docs-Home'
        $pageNames | Should -Not -Contain 'Home'
        Remove-Item $root -Recurse -Force
    }
}

# ─────────────────────────────────────────────────────────────────────────────────────
Describe 'Publish-KnowledgeWiki (uninitialized wiki error)' {
    BeforeAll {
        $script:UninitRoot = New-KnRoot
        Seed-Registry $script:UninitRoot @(
            [pscustomobject]@{ id='kn_001'; domain='TestDomain'; type='url'; title='Test Ref'; ref='https://example.com'; note='test'; added='2026-07-23' }
        )
        $script:PriorGit = Get-Item 'Function:git' -ErrorAction SilentlyContinue
        $script:PriorGh  = Get-Item 'Function:gh'  -ErrorAction SilentlyContinue
        function global:git {
            if ('clone' -in $args) { $global:LASTEXITCODE = 128; return }
            $global:LASTEXITCODE = 0
        }
        function global:gh {
            if ($args[0] -eq 'api' -and 'user' -in $args) { Write-Output 'test-user' }
            elseif ($args[0] -eq 'api') { Write-Output '{"has_wiki":true,"permissions":{"push":true},"name":"test"}' }
            $global:LASTEXITCODE = 0
        }
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_WIKI_TOKEN', 'fake-unit-test-token', 'User')
    }
    AfterAll {
        [System.Environment]::SetEnvironmentVariable('ABIOS_TEST_WIKI_TOKEN', $null, 'User')
        Remove-Item Env:GH_TOKEN -ErrorAction SilentlyContinue
        Remove-Item 'Function:git' -ErrorAction SilentlyContinue
        Remove-Item 'Function:gh'  -ErrorAction SilentlyContinue
        if ($script:PriorGit) { New-Item -Path 'Function:git' -Value $script:PriorGit.ScriptBlock -Force | Out-Null }
        if ($script:PriorGh)  { New-Item -Path 'Function:gh'  -Value $script:PriorGh.ScriptBlock  -Force | Out-Null }
        if ($script:UninitRoot -and (Test-Path $script:UninitRoot)) { Remove-Item $script:UninitRoot -Recurse -Force }
    }

    It 'throws with the actionable step to create the first wiki page via web UI' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-wiki-repo' -TokenVar ABIOS_TEST_WIKI_TOKEN } |
            Should -Throw -ExpectedMessage '*Create the first page*'
    }
    It 'error message includes the wiki URL so the user can navigate directly' {
        { & $script:Engine -Root $script:UninitRoot -Repo 'test-owner/test-wiki-repo' -TokenVar ABIOS_TEST_WIKI_TOKEN } |
            Should -Throw -ExpectedMessage '*github.com/test-owner/test-wiki-repo/wiki*'
    }
}
