#Requires -Modules Pester
<#  Pester tests for Write-KnowledgeTable.ps1. Writes a two-domain registry, regenerates
    the table, and asserts grouping, the generated-header guard, and url link rendering. #>
BeforeAll {
    $script:Engine = Join-Path $PSScriptRoot '..' 'scripts' 'Write-KnowledgeTable.ps1' | Resolve-Path
    $script:Root   = Join-Path ([IO.Path]::GetTempPath()) ("kntbl-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path (Join-Path $script:Root 'knowledge') -Force | Out-Null
    $reg = [pscustomobject]@{ version=1; project='fix'; domains=@('Fabric','DAX')
        references=@(
            [pscustomobject]@{ id='kn_001'; domain='Fabric'; type='url'; title='Cap API'; ref='https://learn.microsoft.com/x'; note='trial->prod'; added='2026-07-07' }
            [pscustomobject]@{ id='kn_002'; domain='DAX';    type='md';  title='Notes';   ref='docs/dax.md';                  note='mine';        added='2026-07-07' }
        ) }
    $reg | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $script:Root 'knowledge' 'registry.json') -Encoding utf8
    & $script:Engine -Root $script:Root | Out-Null
    $script:Md = Get-Content -LiteralPath (Join-Path $script:Root 'knowledge' 'KNOWLEDGE.md') -Raw
}
AfterAll { if ($script:Root -and (Test-Path $script:Root)) { Remove-Item $script:Root -Recurse -Force } }

Describe 'Write-KnowledgeTable' {
    It 'writes the do-not-edit generated header' { $script:Md | Should -Match 'GENERATED by /knowledge' }
    It 'creates a section per domain' {
        $script:Md | Should -Match '(?m)^## DAX'
        $script:Md | Should -Match '(?m)^## Fabric'
    }
    It 'renders urls as markdown links' { $script:Md | Should -Match '\[https://learn\.microsoft\.com/x\]\(https://learn\.microsoft\.com/x\)' }
    It 'renders local refs as inline code' { $script:Md | Should -Match '`docs/dax\.md`' }
}
